yarnPath: .yarn/releases/yarn-4.11.0.cjs
packageExtensions:
  "@prisma/client@*":
    dependencies:
      "@prisma/client-runtime-utils": "*"
  "prisma@*":
    dependencies:
      "@prisma/client": "*"