events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    # Options recommandées pour le proxy
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    location /api/core/ {
      # On retire "/api/core" de l'URL avant de l'envoyer au core-service
      rewrite ^/api/core/(.*) /$1 break;
      proxy_pass http://core-service:3000;
    }

    location /api/room/ {
      # On retire "/api/room" de l'URL avant de l'envoyer au room-service
      rewrite ^/api/room/(.*) /$1 break;
      proxy_pass http://room-service:3000;
    }

    location /api/player/ {
      # On retire "/api/player" de l'URL avant de l'envoyer au player-service
      rewrite ^/api/player/(.*) /$1 break;
      proxy_pass http://player-service:3000;
    }

    location /api/spectator/ {
      # On retire "/api/spectator" de l'URL avant de l'envoyer au spectator-service
      rewrite ^/api/spectator/(.*) /$1 break;
      proxy_pass http://spectator-service:3000;
    }
  }
}
